"use client";
import { useMemo, useState } from "react";
import { Check, RotateCcw } from "lucide-react";
import { chapterRequired, chapters, factOptions } from "../../prompt-studio/data";

export default function ChapterFactsPage() {
  const [active, setActive] = useState(chapters[0].key);
  const [configured, setConfigured] = useState<Record<string,string[]>>(() => Object.fromEntries(chapters.map(c=>[c.key,[...c.defaults]])));
  const chapter = chapters.find(c=>c.key===active)!; const selected = configured[active];
  const grouped = useMemo(()=>factOptions.reduce<Record<string,typeof factOptions>>((all,item)=>{(all[item.group]??=[]).push(item);return all;},{}),[]);
  const toggle = (key:string) => { if(chapterRequired[active]?.includes(key)) return; setConfigured(all=>({...all,[active]:selected.includes(key)?selected.filter(v=>v!==key):[...selected,key]})); };
  return <section><header className="mb-5"><h2 className="text-2xl">章节事实配置</h2><p className="mt-1 text-sm" style={{color:"var(--ink-soft)"}}>配置十个章节默认可读取的前置计算数据；必需项被锁定，后续调整不需要改动编排代码。</p></header><div className="grid border lg:grid-cols-[18rem_1fr]" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}><nav aria-label="章节列表" className="border-b lg:border-b-0 lg:border-r" style={{borderColor:"var(--line)"}}>{chapters.map(c=><button key={c.key} type="button" onClick={()=>setActive(c.key)} className="flex w-full items-center gap-3 border-b px-4 py-3 text-left text-sm" style={{borderColor:"var(--line-soft)",background:active===c.key?"var(--gold-soft)":"transparent"}}><span style={{color:"var(--gold-deep)"}}>{String(c.no).padStart(2,"0")}</span><span><strong className="block font-medium">{c.title}</strong><small style={{color:"var(--ink-faint)"}}>{c.key}</small></span></button>)}</nav><div className="p-5"><div className="mb-5 flex flex-wrap items-start justify-between gap-3 border-b pb-4" style={{borderColor:"var(--line)"}}><div><h3 className="text-xl">{chapter.title}</h3><p className="text-sm" style={{color:"var(--ink-soft)"}}>{chapter.purpose}</p></div><button type="button" onClick={()=>setConfigured(all=>({...all,[active]:[...chapter.defaults]}))} className="btn-ghost flex items-center gap-1 px-3 py-2 text-sm"><RotateCcw size={14}/>恢复默认</button></div><div className="grid gap-x-8 gap-y-5 md:grid-cols-2 xl:grid-cols-3">{Object.entries(grouped).map(([group,items])=><fieldset key={group}><legend className="mb-2 text-sm font-medium">{group}</legend>{items.map(item=>{const required=chapterRequired[active]?.includes(item.key);return <label key={item.key} className="flex cursor-pointer items-start gap-2 border-t py-2 text-sm" style={{borderColor:"var(--line-soft)"}}><input type="checkbox" className="mt-1 accent-amber-700" checked={selected.includes(item.key)} disabled={required} onChange={()=>toggle(item.key)}/><span><span>{item.label}{required&&<em className="ml-1 not-italic" style={{color:"var(--gold-deep)"}}><Check className="inline" size={12}/>必需</em>}</span><small className="block font-mono" style={{color:"var(--ink-faint)"}}>{item.key}</small></span></label>})}</fieldset>)}</div></div></div></section>;
}
