"use client";

import { createLLMModel, fetchLLMCatalog, fetchLLMModels, fetchLLMProviders, updateLLMModel, type LLMModelConfig, type LLMProviderConfig, type LLMProviderPreset } from "@/lib/admin-api";
import { ChevronDown, ChevronUp, Plus, Search } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

type Form={provider_id:number;name:string;model_id:string;priority:number;max_retries:number;enabled:boolean};
const empty:Form={provider_id:0,name:"",model_id:"",priority:1,max_retries:3,enabled:true};

export default function ModelsPage(){
 const [rows,setRows]=useState<LLMModelConfig[]>([]),[providers,setProviders]=useState<LLMProviderConfig[]>([]),[catalog,setCatalog]=useState<LLMProviderPreset[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10),[q,setQ]=useState(""),[providerFilter,setProviderFilter]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState<LLMModelConfig|null>(null),[form,setForm]=useState<Form>(empty),[preset,setPreset]=useState(""),[saving,setSaving]=useState(false);
 const pages=Math.max(1,Math.ceil(total/pageSize));
 const load=useCallback(async()=>{setLoading(true);setError("");try{const data=await fetchLLMModels(page,pageSize,q,providerFilter||undefined);setRows(data.items);setTotal(data.total)}catch{setError("模型读取失败，请检查后端服务后重试。")}finally{setLoading(false)}},[page,pageSize,q,providerFilter]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{Promise.all([fetchLLMProviders(1,100),fetchLLMCatalog()]).then(([p,c])=>{setProviders(p.items);setCatalog(c.providers)}).catch(()=>setError("供应商或模型目录读取失败。"))},[]);
 const activePreset=useMemo(()=>{const provider=providers.find(x=>x.id===form.provider_id);return catalog.find(x=>x.code===provider?.code)},[catalog,form.provider_id,providers]);
 const begin=(row?:LLMModelConfig)=>{setEditing(row??null);setPreset(row?.model_id??"");setForm(row?{provider_id:row.provider_id,name:row.name,model_id:row.model_id,priority:row.priority,max_retries:row.max_retries,enabled:row.enabled}:{...empty,provider_id:providers[0]?.id??0,priority:total+1});setOpen(true)};
 const chooseProvider=(provider_id:number)=>{setPreset("");setForm(v=>({...v,provider_id,model_id:"",name:""}))};
 const chooseModel=(modelID:string)=>{setPreset(modelID);if(modelID==="custom"){setForm(v=>({...v,model_id:"",name:""}));return}const item=activePreset?.models.find(x=>x.id===modelID);setForm(v=>({...v,model_id:modelID,name:item?.name??v.name}))};
 const save=async()=>{setSaving(true);setError("");try{if(editing)await updateLLMModel(editing.id,form);else await createLLMModel(form);setOpen(false);await load()}catch{setError("保存失败，请确认供应商、模型名称、model 参数和优先级填写正确。")}finally{setSaving(false)}};
 const toggle=async(row:LLMModelConfig)=>{try{await updateLLMModel(row.id,{provider_id:row.provider_id,name:row.name,model_id:row.model_id,priority:row.priority,max_retries:row.max_retries,enabled:!row.enabled});await load()}catch{setError("状态更新失败。")}};
 const move=async(row:LLMModelConfig,delta:number)=>{const target=rows[rows.findIndex(x=>x.id===row.id)+delta];if(!target)return;try{await Promise.all([updateLLMModel(row.id,{provider_id:row.provider_id,name:row.name,model_id:row.model_id,priority:target.priority,max_retries:row.max_retries,enabled:row.enabled}),updateLLMModel(target.id,{provider_id:target.provider_id,name:target.name,model_id:target.model_id,priority:row.priority,max_retries:target.max_retries,enabled:target.enabled})]);await load()}catch{setError("优先级调整失败。")}};
 return <section className="border" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}>
  <header className="flex flex-wrap items-start justify-between gap-3 border-b px-5 py-4" style={{borderColor:"var(--line)"}}><div><h2 className="text-lg font-medium">模型配置</h2><p className="mt-1 text-sm" style={{color:"var(--ink-faint)"}}>模型必须先选择已配置供应商，再从该供应商的主流模型中选择；也可填写自定义 model。</p></div><button disabled={!providers.length} onClick={()=>begin()} className="btn-gold flex items-center gap-2 px-4 py-2 text-sm"><Plus size={15}/>新增模型</button></header>
  <div className="flex flex-wrap gap-3 border-b px-5 py-3" style={{borderColor:"var(--line-soft)"}}><label className="flex min-w-64 flex-1 items-center gap-2 border px-3" style={{borderColor:"var(--line)"}}><Search size={15}/><input aria-label="搜索模型" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="搜索模型名称或 model 参数" className="w-full bg-transparent py-2 outline-none"/></label><select aria-label="按供应商筛选" value={providerFilter} onChange={e=>{setProviderFilter(Number(e.target.value));setPage(1)}} className="border px-3 py-2" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}><option value={0}>全部供应商</option>{providers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>
  {error&&<p role="alert" className="border-b px-5 py-3 text-sm text-red-700" style={{borderColor:"var(--line-soft)"}}>{error}</p>}
  <div className="overflow-x-auto"><table className="w-full min-w-[940px] text-left text-sm"><thead><tr className="border-b" style={{borderColor:"var(--line-soft)"}}>{["优先级","模型名称","供应商","model","最大重试","状态","排序","操作"].map(x=><th key={x} className="px-4 py-3 font-medium">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={8} className="px-5 py-12 text-center">正在读取模型…</td></tr>:rows.length===0?<tr><td colSpan={8} className="px-5 py-12 text-center">{providers.length?"暂无模型，请新增模型。":"请先前往“供应商配置”新增供应商。"}</td></tr>:rows.map((item,index)=><tr key={item.id} className="border-b last:border-0" style={{borderColor:"var(--line-soft)",opacity:item.enabled?1:.58}}><td className="px-4 py-4"><span className="inline-flex h-8 w-8 items-center justify-center border" style={{borderColor:"var(--gold-deep)",color:"var(--gold-deep)"}}>{item.priority}</span></td><td className="px-4 py-4 font-medium">{item.name}</td><td className="px-4 py-4">{item.provider.name}</td><td className="px-4 py-4 font-mono text-xs">{item.model_id}</td><td className="px-4 py-4">{item.max_retries} 次</td><td className="px-4 py-4"><button className="underline underline-offset-4" onClick={()=>toggle(item)}>{item.enabled?"已启用":"已停用"}</button></td><td className="px-4 py-4"><div className="flex gap-1"><button aria-label={`上移${item.name}`} disabled={index===0} onClick={()=>move(item,-1)} className="btn-ghost p-1"><ChevronUp size={15}/></button><button aria-label={`下移${item.name}`} disabled={index===rows.length-1} onClick={()=>move(item,1)} className="btn-ghost p-1"><ChevronDown size={15}/></button></div></td><td className="px-4 py-4"><button onClick={()=>begin(item)}>编辑</button></td></tr>)}</tbody></table></div>
  <footer className="flex flex-wrap items-center justify-between gap-3 border-t px-5 py-4 text-sm" style={{borderColor:"var(--line-soft)"}}><span style={{color:"var(--ink-faint)"}}>共 {total} 个模型</span><div className="flex items-center gap-3"><label>每页 <select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}} className="border px-2 py-1" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}><option>10</option><option>20</option><option>50</option></select></label><button className="btn-ghost px-3 py-1" disabled={page===1} onClick={()=>setPage(page-1)}>上一页</button><span>{page}/{pages}</span><button className="btn-ghost px-3 py-1" disabled={page===pages} onClick={()=>setPage(page+1)}>下一页</button></div></footer>
  {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section role="dialog" aria-modal="true" aria-labelledby="model-dialog-title" className="w-full max-w-xl border p-5 shadow-2xl" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}><h2 id="model-dialog-title" className="text-xl">{editing?"编辑模型":"新增模型"}</h2><div className="mt-5 grid gap-4"><label className="text-sm">所属供应商<select value={form.provider_id} onChange={e=>chooseProvider(Number(e.target.value))} className="mt-1 w-full border px-3 py-2" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}><option value={0}>先选择供应商</option>{providers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-sm">该供应商的常见模型<select disabled={!form.provider_id} value={activePreset?.models.some(x=>x.id===preset)?preset:"custom"} onChange={e=>chooseModel(e.target.value)} className="mt-1 w-full border px-3 py-2" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}>{activePreset?.models.map(x=><option key={x.id} value={x.id}>{x.name} · {x.id}</option>)}<option value="custom">自定义 model</option></select></label><Field label="模型名称" value={form.name} onChange={name=>setForm(v=>({...v,name}))}/><Field label="model 参数" value={form.model_id} onChange={model_id=>{setPreset("custom");setForm(v=>({...v,model_id}))}}/><div className="grid grid-cols-2 gap-3"><NumberField label="优先级" value={form.priority} min={1} max={9999} onChange={priority=>setForm(v=>({...v,priority}))}/><NumberField label="最大重试次数" value={form.max_retries} min={0} max={10} onChange={max_retries=>setForm(v=>({...v,max_retries}))}/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.enabled} onChange={e=>setForm(v=>({...v,enabled:e.target.checked}))}/>启用模型</label></div><div className="mt-6 flex justify-end gap-3"><button className="btn-ghost px-4 py-2" onClick={()=>setOpen(false)}>取消</button><button disabled={saving||!form.provider_id||!form.name||!form.model_id} className="btn-gold px-4 py-2" onClick={save}>{saving?"保存中…":"保存"}</button></div></section></div>}
 </section>
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(x:string)=>void}){return <label className="text-sm">{label}<input value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full border px-3 py-2" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}/></label>}
function NumberField({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(x:number)=>void}){return <label className="text-sm">{label}<input type="number" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))} className="mt-1 w-full border px-3 py-2" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}/></label>}
