"use client";

import { useEffect, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { CheckCircle2, Clock3, FileJson2, Languages, ScrollText, X, XCircle } from "lucide-react";
import { fetchReportChapterArtifact, fetchReportChapters } from "@/lib/admin-api";

function ParsedContent({ value }: { value: unknown }) {
  if (!value || typeof value !== "object") return <p className="whitespace-pre-wrap text-sm leading-7">{String(value ?? "暂无正文")}</p>;
  const root = value as Record<string, unknown>; const modules = (root["模块"] ?? root.modules) as unknown;
  if (!Array.isArray(modules)) return <pre className="overflow-auto whitespace-pre-wrap text-sm leading-7">{JSON.stringify(value, null, 2)}</pre>;
  return <div className="space-y-6">{modules.map((item, index) => { const section = item as Record<string, unknown>; return <article key={index} className="border-t pt-5 first:border-t-0 first:pt-0" style={{ borderColor: "var(--line)" }}><h3 className="text-lg">{String(section["名称"] ?? section.name ?? `模块 ${index + 1}`)}</h3><p className="mt-3 whitespace-pre-wrap text-[15px] leading-8">{String(section["正文"] ?? section.content ?? section.body ?? "")}</p></article>; })}</div>;
}

type ArtifactType = "prompt" | "terminology" | "raw_output";
const artifactTitles: Record<ArtifactType, string> = { prompt: "最终 Prompt", terminology: "专业术语快照", raw_output: "模型原始输出" };

function ArtifactDialog({ reportId, chapterId, type, locale, onClose }: { reportId: string; chapterId: number; type: ArtifactType; locale: string; onClose: () => void }) {
  const closeRef = useRef<HTMLButtonElement>(null);
  const artifact = useQuery({ queryKey: ["admin-report-chapter-artifact", reportId, chapterId, type], queryFn: () => fetchReportChapterArtifact(reportId, chapterId, type), retry: false });
  useEffect(() => { closeRef.current?.focus(); const handler = (event: KeyboardEvent) => event.key === "Escape" && onClose(); window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [onClose]);
  const value = artifact.data?.value; const chinese = type === "terminology" && locale === "zh"; const historicalMissing = type === "terminology" && (value === null || value === undefined); const empty = type === "terminology" && Array.isArray(value) && value.length === 0;
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4" role="presentation" onMouseDown={event => event.target === event.currentTarget && onClose()}><section role="dialog" aria-modal="true" aria-labelledby="chapter-artifact-title" className="max-h-[90vh] w-full max-w-6xl overflow-hidden border shadow-2xl" style={{ borderColor: "var(--line)", background: "var(--bg-card)" }}><header className="flex items-center justify-between border-b px-5 py-4" style={{ borderColor: "var(--line)" }}><div><h2 id="chapter-artifact-title" className="text-xl">{artifactTitles[type]}</h2><p className="mt-1 text-xs" style={{ color: "var(--ink-faint)" }}>该章节生成时冻结的只读数据。</p></div><button ref={closeRef} type="button" onClick={onClose} aria-label={`关闭${artifactTitles[type]}`} className="btn-ghost p-2"><X size={19} /></button></header><div className="max-h-[78vh] overflow-auto p-5">{artifact.isLoading ? <p className="text-sm">正在按需读取…</p> : artifact.isError ? <p className="text-sm text-red-800">数据读取失败。</p> : chinese ? <p className="border-l-2 border-amber-700 px-4 py-3 text-sm">当前报告语言为中文，无需翻译术语。</p> : historicalMissing ? <p className="border-l-2 border-amber-700 px-4 py-3 text-sm">该历史报告生成时未保存专业术语快照。</p> : empty ? <p className="border-l-2 border-amber-700 px-4 py-3 text-sm">本章未使用需要指定译名的专业术语。</p> : <pre className="whitespace-pre-wrap text-xs leading-6">{type === "terminology" ? JSON.stringify(value, null, 2) : String(value || "暂无数据")}</pre>}</div></section></div>;
}

export function ChapterTracePanel({ reportId, locale }: { reportId: string; locale: string }) {
  const chapters = useQuery({ queryKey: ["admin-report-chapters", reportId], queryFn: () => fetchReportChapters(reportId), retry: false });
  const [chapterId, setChapterId] = useState<number>(); const [artifact, setArtifact] = useState<ArtifactType>();
  useEffect(() => { if (!chapterId && chapters.data?.items[0]) setChapterId(chapters.data.items[0].id); }, [chapterId, chapters.data]);
  const content = useQuery({ queryKey: ["admin-report-chapter-artifact", reportId, chapterId, "content"], queryFn: () => fetchReportChapterArtifact(reportId, chapterId!, "content"), enabled: !!chapterId, retry: false });
  const selected = chapters.data?.items.find(item => item.id === chapterId);
  return <div className="grid gap-5 xl:grid-cols-[18rem_minmax(0,1fr)]"><aside className="border" style={{ borderColor: "var(--line)", background: "var(--bg-card)" }} aria-label="十章列表"><h2 className="border-b px-4 py-3 text-lg" style={{ borderColor: "var(--line)" }}>十章执行结果</h2>{chapters.isLoading ? <p className="p-4 text-sm">正在加载…</p> : chapters.isError ? <p role="alert" className="p-4 text-sm text-red-800">章节读取失败</p> : chapters.data?.items.map(item => <button type="button" key={item.id} onClick={() => { setChapterId(item.id); setArtifact(undefined); }} aria-current={chapterId === item.id ? "page" : undefined} className={`flex w-full items-center gap-3 border-b px-4 py-3 text-left ${chapterId === item.id ? "bg-amber-50" : "hover:bg-black/[0.025]"}`} style={{ borderColor: "var(--line-soft)" }}><span className="w-6 font-mono text-xs">{String(item.chapter_no).padStart(2, "0")}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm">{item.title}</span><span className="mt-1 block text-xs" style={{ color: "var(--ink-faint)" }}>尝试 {item.attempt_count} 次</span></span>{item.status === "succeeded" ? <CheckCircle2 size={16} className="text-emerald-800" /> : item.status === "failed" ? <XCircle size={16} className="text-red-800" /> : <Clock3 size={16} className="text-amber-800" />}</button>)}</aside>
    <section className="min-w-0 border" style={{ borderColor: "var(--line)", background: "var(--bg-card)" }}>{!selected ? <p className="p-6 text-sm">请选择章节。</p> : <><header className="border-b px-6 py-5" style={{ borderColor: "var(--line)" }}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs text-amber-800">第 {selected.chapter_no} 章</p><h2 className="mt-1 text-xl">{selected.title}</h2></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setArtifact("prompt")} className="btn-ghost inline-flex items-center gap-2 border px-3 py-2 text-sm"><ScrollText size={15} />最终 Prompt</button><button type="button" onClick={() => setArtifact("terminology")} className="btn-ghost inline-flex items-center gap-2 border px-3 py-2 text-sm"><Languages size={15} />专业术语快照</button><button type="button" onClick={() => setArtifact("raw_output")} className="btn-ghost inline-flex items-center gap-2 border px-3 py-2 text-sm"><FileJson2 size={15} />模型原始输出</button></div></div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-xs" style={{ color: "var(--ink-faint)" }}><span>状态：{selected.status}</span><span>采用 attempt：#{selected.selected_attempt_id ?? "—"}</span><span>校验：{selected.validation_status}</span><span>输出哈希：{selected.output_hash || "—"}</span></div></header><div className="p-6">{content.isLoading ? <p className="text-sm">正在按需读取正文…</p> : content.isError ? <p className="text-sm text-red-800">章节正文读取失败。</p> : <ParsedContent value={content.data?.value} />}</div></>}</section>
    {artifact && chapterId && <ArtifactDialog reportId={reportId} chapterId={chapterId} type={artifact} locale={locale} onClose={() => setArtifact(undefined)} />}</div>;
}
