"use client";
import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { fetchPromptRegistry, previewReportPrompt } from "@/lib/admin-api";

function CodeBlock({title,value}:{title:string;value:unknown}) { return <details className="border" style={{borderColor:"var(--line)"}} open><summary className="cursor-pointer px-4 py-3 text-sm font-medium">{title}</summary><pre className="max-h-96 overflow-auto whitespace-pre-wrap border-t p-4 font-mono text-xs leading-6" style={{borderColor:"var(--line-soft)",background:"var(--bg)"}}>{typeof value==="string"?value:JSON.stringify(value,null,2)}</pre></details> }

export function PromptPreviewPanel({reportId}:{reportId:string}) {
  const [chapter,setChapter]=useState("destiny_depth"); const [locale,setLocale]=useState("zh");
  const registry=useQuery({queryKey:["admin-prompt-registry"],queryFn:fetchPromptRegistry});
  const preview=useMutation({mutationFn:()=>previewReportPrompt(reportId,chapter,locale)});
  const disabled=registry.isLoading||registry.isError;
  return <section className="space-y-4"><div><h2 className="text-[19px] font-medium">Prompt 编排预览</h2><p className="mt-1 text-[13px]" style={{color:"var(--ink-faint)"}}>读取该报告不可变事实快照，按章节白名单生成最终指令；不会发起外部调用。</p></div><div className="grid gap-3 border p-4 md:grid-cols-[1fr_12rem_auto]" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}><label><span className="mb-1 block text-xs">章节</span><select className="w-full border px-3 py-2 text-sm" value={chapter} disabled={disabled} onChange={e=>setChapter(e.target.value)}>{registry.data?.chapters.map(item=><option key={item.key} value={item.key}>{item.name} · {item.key}</option>)}</select></label><label><span className="mb-1 block text-xs">目标语言</span><select className="w-full border px-3 py-2 text-sm" value={locale} disabled={disabled} onChange={e=>setLocale(e.target.value)}>{registry.data?.locales.map(item=><option key={item.code} value={item.code}>{item.name} · {item.code}</option>)}</select></label><button type="button" className="btn-gold self-end px-4 py-2 text-sm" disabled={preview.isPending||disabled} onClick={()=>preview.mutate()}>{preview.isPending?"生成中…":"生成预览"}</button></div>{registry.isLoading&&<p role="status" className="text-sm" style={{color:"var(--ink-faint)"}}>正在加载十章注册表…</p>}{registry.isError&&<p role="alert" className="text-sm text-red-800">十章注册表加载失败。</p>}{preview.isError&&<p role="alert" className="border p-4 text-sm text-red-800" style={{borderColor:"var(--line)"}}>预览失败：请确认该报告存在新版事实快照，并检查章节和语言设置。</p>}{preview.data&&<div className="space-y-3"><div className="flex flex-wrap gap-4 border px-4 py-3 text-xs" style={{borderColor:"var(--line)",background:"var(--gold-soft)"}}><span>章节：{preview.data.chapter.name}</span><span>locale：{preview.data.locale.code}</span><span>事实：{preview.data.chapter.default_facts.length} 项</span><span>facts_hash：{preview.data.facts_hash}</span><span>版本：{preview.data.registry_version}</span></div><CodeBlock title="System Prompt" value={preview.data.system_prompt}/><CodeBlock title="User Prompt" value={preview.data.user_prompt}/><CodeBlock title="实际事实输入 JSON" value={preview.data.input_facts}/><CodeBlock title="输出 JSON Schema" value={preview.data.output_schema}/></div>}</section>;
}
