"use client";

import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { BaziBaseSummary, fetchBaziBasePage, fetchBaziBaseSummary, LocalizedNames } from "@/lib/admin-api";

type Row = Record<string, unknown> & { code?: string; names?: LocalizedNames; category?: string; type?: string; scope?: string; element?: string; members?: string[]; value?: number; weight?: number };
type Tab = { key: string; label: string };
const tabs: Tab[] = [{key:"elements",label:"五行"},{key:"stems",label:"天干"},{key:"branches",label:"地支与藏干"},{key:"ten-gods",label:"十神"},{key:"relations",label:"干支关系"},{key:"strength-rules",label:"身强规则"},{key:"display-dictionary",label:"显示字典"}];
const PAGE_SIZE=20;

export default function BaziBasePage(){
  const [summary,setSummary]=useState<BaziBaseSummary|null>(null);const [tab,setTab]=useState("elements");const [rows,setRows]=useState<Row[]>([]);const [total,setTotal]=useState(0);const [page,setPage]=useState(1);const [query,setQuery]=useState("");const [activeQuery,setActiveQuery]=useState("");const [relationType,setRelationType]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [selected,setSelected]=useState<Row|null>(null);const dialogRef=useRef<HTMLDialogElement>(null);
  useEffect(()=>{fetchBaziBaseSummary().then(setSummary).catch(()=>setError("基础数据概览加载失败，请稍后重试。"));},[]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const data=await fetchBaziBasePage(tab,{q:activeQuery,type:tab==="relations"?relationType:undefined,page,page_size:PAGE_SIZE});setRows(data.items??[]);setTotal(data.total??0);}catch{setError("基础数据加载失败，请稍后重试。");}finally{setLoading(false);}},[tab,activeQuery,relationType,page]);
  useEffect(()=>{void load();},[load]);useEffect(()=>{if(selected)dialogRef.current?.showModal();else dialogRef.current?.close();},[selected]);
  const switchTab=(key:string)=>{setTab(key);setPage(1);setQuery("");setActiveQuery("");setRelationType("");};
  const search=(event:FormEvent)=>{event.preventDefault();setPage(1);setActiveQuery(query.trim());};const pageCount=Math.max(1,Math.ceil(total/PAGE_SIZE));
  return <div className="mx-auto max-w-7xl">
    <header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-medium">命理基础数据</h1><p className="mt-1 text-sm" style={{color:"var(--ink-soft)"}}>只读查看确定性排盘规则。修改规则必须发布新版本，历史报告不会被覆盖。</p></div>{summary&&<div className="border px-4 py-3 text-sm" style={{background:"var(--bg-card)",borderColor:"var(--line)"}}><span className="font-medium">{summary.version}</span><span className="ml-3" style={{color:summary.valid?"var(--gold-deep)":"#991b1b"}}>{summary.valid?"完整性校验通过":"校验失败"}</span></div>}</header>
    {summary&&<section aria-label="数据概览" className="mb-6 grid grid-cols-2 border sm:grid-cols-5" style={{borderColor:"var(--line)"}}>{([["五行",summary.elements],["天干",summary.stems],["地支",summary.branches],["关系",summary.relations],["十神规则",summary.ten_god_rules]] as [string,number][]).map(([label,value])=><div key={label} className="border-r p-4 last:border-r-0" style={{borderColor:"var(--line-soft)"}}><div className="text-2xl font-[var(--serif)]">{value}</div><div className="mt-1 text-xs" style={{color:"var(--ink-soft)"}}>{label}</div></div>)}</section>}
    <nav aria-label="基础数据分类" className="mb-5 flex overflow-x-auto border-b" style={{borderColor:"var(--line)"}}>{tabs.map(item=><button key={item.key} type="button" aria-current={tab===item.key?"page":undefined} onClick={()=>switchTab(item.key)} className="shrink-0 border-b-2 px-4 py-3 text-sm" style={{borderColor:tab===item.key?"var(--gold-deep)":"transparent",color:tab===item.key?"var(--gold-deep)":"var(--ink-soft)"}}>{item.label}</button>)}</nav>
    <form onSubmit={search} className="mb-4 flex flex-wrap gap-2"><label htmlFor="base-search" className="sr-only">搜索基础数据</label><input id="base-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索代码、中文或多语言名称" className="min-w-64 flex-1 border px-3 py-2" style={{background:"var(--bg-card)",borderColor:"var(--line)"}}/>{tab==="relations"&&<select aria-label="关系类型" value={relationType} onChange={e=>{setRelationType(e.target.value);setPage(1);}} className="border px-3 py-2" style={{background:"var(--bg-card)",borderColor:"var(--line)"}}><option value="">全部关系</option><option value="combination">天干五合</option><option value="six_combination">六合</option><option value="three_harmony">三合</option><option value="half_harmony">半合</option><option value="three_meeting">三会</option><option value="clash">冲</option><option value="punishment">刑</option><option value="harm">害</option><option value="break">破</option></select>}<button type="submit" className="btn-gold px-5 py-2">搜索</button></form>
    {error&&<p role="alert" className="mb-4 border px-4 py-3 text-sm text-red-800" style={{background:"var(--bg-card)",borderColor:"var(--line)"}}>{error}</p>}
    <BaseTable rows={rows} loading={loading} onSelect={setSelected}/><footer className="mt-4 flex items-center justify-between text-sm"><span style={{color:"var(--ink-soft)"}}>共 {total} 条</span><div className="flex items-center gap-3"><button type="button" disabled={page<=1||loading} onClick={()=>setPage(v=>v-1)} className="border px-3 py-1.5 disabled:opacity-40" style={{borderColor:"var(--line)"}}>上一页</button><span>第 {page} / {pageCount} 页</span><button type="button" disabled={page>=pageCount||loading} onClick={()=>setPage(v=>v+1)} className="border px-3 py-1.5 disabled:opacity-40" style={{borderColor:"var(--line)"}}>下一页</button></div></footer>
    <dialog ref={dialogRef} onClose={()=>setSelected(null)} aria-labelledby="base-detail-title" className="w-[min(42rem,calc(100%-2rem))] border p-0 backdrop:bg-black/35" style={{background:"var(--bg-card)",borderColor:"var(--line)"}}>{selected&&<div><header className="flex items-start justify-between border-b p-5" style={{borderColor:"var(--line)"}}><div><h2 id="base-detail-title" className="text-xl">{selected.names?.zh??selected.code??"规则详情"}</h2><p className="mt-1 text-sm" style={{color:"var(--ink-soft)"}}>版本 {summary?.version}</p></div><button type="button" onClick={()=>setSelected(null)} aria-label="关闭详情" className="text-2xl leading-none">×</button></header><dl className="grid grid-cols-[9rem_1fr] gap-x-4 gap-y-3 p-5 text-sm">{Object.entries(selected).map(([key,value])=><DetailRow key={key} label={key} value={value}/>)}</dl></div>}</dialog>
  </div>;
}

function BaseTable({rows,loading,onSelect}:{rows:Row[];loading:boolean;onSelect:(row:Row)=>void}){return <div className="overflow-x-auto border" style={{background:"var(--bg-card)",borderColor:"var(--line)"}}><table className="w-full min-w-[860px] border-collapse text-left text-sm"><thead><tr className="border-b" style={{borderColor:"var(--line)"}}>{["代码 / 符号","中文","English","日本語","한국어","分类 / 数值","操作"].map(v=><th key={v} className="px-4 py-3 font-medium">{v}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={7} className="px-4 py-12 text-center" aria-live="polite">加载中…</td></tr>:rows.length===0?<tr><td colSpan={7} className="px-4 py-12 text-center">没有找到匹配数据</td></tr>:rows.map((row,index)=><tr key={`${row.code??"row"}-${index}`} className="border-b last:border-0" style={{borderColor:"var(--line-soft)"}}><td className="px-4 py-3 font-medium">{row.code??"—"}</td><td className="px-4 py-3">{row.names?.zh??formatMembers(row.members)}</td><td className="px-4 py-3">{row.names?.en??"—"}</td><td className="px-4 py-3">{row.names?.ja??"—"}</td><td className="px-4 py-3">{row.names?.ko??"—"}</td><td className="px-4 py-3">{[row.category,row.scope,row.type,row.element,row.value??row.weight].filter(v=>v!==undefined&&v!=="").join(" · ")||"—"}</td><td className="px-4 py-3"><button type="button" onClick={()=>onSelect(row)} className="px-2 py-1" style={{color:"var(--gold-deep)"}}>详情</button></td></tr>)}</tbody></table></div>}
function DetailRow({label,value}:{label:string;value:unknown}){return <><dt className="font-medium" style={{color:"var(--ink-soft)"}}>{label}</dt><dd className="min-w-0 whitespace-pre-wrap break-words">{typeof value==="object"?JSON.stringify(value,null,2):String(value)}</dd></>}
function formatMembers(value:unknown){return Array.isArray(value)?value.join(" · "):"—"}
