-- Authenticated free chart history. Independent from profiles and reports.
CREATE TABLE free_chart_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  gender TINYINT NOT NULL,
  calendar_type TINYINT NOT NULL,
  birth_year SMALLINT NOT NULL,
  birth_month TINYINT NOT NULL,
  birth_day TINYINT NOT NULL,
  birth_hour TINYINT NOT NULL,
  birth_minute TINYINT NOT NULL,
  is_leap_month TINYINT(1) NOT NULL DEFAULT 0,
  country_code VARCHAR(8) NULL,
  country_name VARCHAR(96) NULL,
  region_code VARCHAR(32) NULL,
  region_name VARCHAR(96) NULL,
  city VARCHAR(96) NULL,
  place_id VARCHAR(128) NULL,
  display_name VARCHAR(256) NULL,
  timezone_id VARCHAR(64) NOT NULL,
  latitude DECIMAL(9,6) NOT NULL,
  longitude DECIMAL(9,6) NOT NULL,
  chart_hash CHAR(64) NOT NULL,
  chart_data JSON NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_free_chart_user_created (user_id, created_at DESC),
  KEY idx_free_chart_hash (chart_hash),
  CONSTRAINT fk_free_chart_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
