"use client";
import { useState } from "react";
import { Calculator, ChevronRight, Plus, RotateCcw, Search, Trash2 } from "lucide-react";
import type { CalculationRecord } from "./data";

export function CalculationRecords({records,activeId,onSelect,onCreate,onDelete}:{records:CalculationRecord[];activeId:number;onSelect:(id:number)=>void;onCreate:()=>void;onDelete:(id:number)=>void}){
  const [query,setQuery]=useState("");
  const visible=records.filter(r=>`${r.name}${r.birth}${r.place}`.toLowerCase().includes(query.toLowerCase()));
  return <section aria-labelledby="records-title" className="border" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}>
    <header className="border-b p-4" style={{borderColor:"var(--line)"}}><div className="flex items-center justify-between"><div><h2 id="records-title" className="text-lg">计算档案</h2><p className="mt-1 text-xs" style={{color:"var(--ink-faint)"}}>先计算并保存，再用于章节编排</p></div><button type="button" onClick={onCreate} className="btn-gold flex items-center gap-1 px-3 py-2 text-sm"><Plus size={15}/>新增</button></div><label className="mt-4 flex items-center gap-2 border px-3 py-2" style={{borderColor:"var(--line-soft)"}}><Search size={15} aria-hidden/><span className="sr-only">搜索计算档案</span><input value={query} onChange={e=>setQuery(e.target.value)} className="min-w-0 flex-1 bg-transparent text-sm outline-none" placeholder="搜索名称、地区或时间"/></label></header>
    <div className="max-h-[660px] overflow-y-auto">{visible.length===0?<div className="p-8 text-center text-sm" style={{color:"var(--ink-faint)"}}>没有匹配的计算档案</div>:visible.map(record=>{const active=record.id===activeId;return <article key={record.id} className="border-b p-4 last:border-0" style={{borderColor:"var(--line-soft)",background:active?"var(--gold-soft)":"transparent"}}><button type="button" onClick={()=>onSelect(record.id)} className="w-full text-left focus-visible:outline focus-visible:outline-2" style={{outlineColor:"var(--gold)"}}><div className="flex items-start justify-between gap-2"><div><div className="font-medium">{record.name}</div><div className="mt-1 text-xs" style={{color:"var(--ink-soft)"}}>{record.birth} · {record.place}</div></div><ChevronRight size={16} style={{color:active?"var(--gold-deep)":"var(--ink-faint)"}}/></div><div className="mt-3 flex gap-1">{record.pillars.map((p,i)=><span key={i} className="border px-2 py-0.5 text-xs" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}>{p}</span>)}</div><div className="mt-3 flex items-center justify-between text-xs" style={{color:"var(--ink-faint)"}}><span>{record.versions} 个计算版本</span><span>{record.updatedAt}</span></div></button><div className="mt-3 flex gap-3 border-t pt-3 text-xs" style={{borderColor:"var(--line-soft)"}}><button type="button" className="flex items-center gap-1" style={{color:"var(--gold-deep)"}}><Calculator size={13}/>查看结果</button><button type="button" className="flex items-center gap-1"><RotateCcw size={13}/>重新计算</button><button type="button" onClick={()=>onDelete(record.id)} className="ml-auto flex items-center gap-1 text-red-800"><Trash2 size={13}/>删除</button></div></article>})}</div>
  </section>;
}
