"use client";
import {useMemo,useState} from "react";
import {Check,LoaderCircle,RotateCcw,Save,Search} from "lucide-react";
import {resetPromptConfig,savePromptConfig,type PromptRegistryResponse} from "@/lib/admin-api";

const labels:Record<string,[string,string]>={chart:["四柱与命盘","命盘"],element_strength:["五行力量","力量与关系"],day_master_strength:["身强弱与计算依据","确定性推断"],ten_god_structure:["十神结构","确定性推断"],stem_relations:["天干关系","力量与关系"],branch_relations:["地支关系","力量与关系"],pattern_candidates:["格局候选","确定性推断"],climate:["调候","确定性推断"],disease:["病药","确定性推断"],mediation:["通关","确定性推断"],useful_god:["喜用神与模拟依据","确定性推断"],favorable_elements:["喜忌仇闲","确定性推断"],luck_cycles:["大运","运势"],annual_fortunes:["未来十年流年","运势"]};

export function ChapterFactConfig({registry,activeKey,value,onChange}:{registry:PromptRegistryResponse;activeKey:string;value:string[];onChange:(keys:string[])=>void}){
 const chapter=registry.chapters.find(c=>c.key===activeKey)!;const [search,setSearch]=useState("");const [saving,setSaving]=useState(false);const [notice,setNotice]=useState("");
 const groups=useMemo(()=>{const facts=Array.from(new Set(registry.chapters.flatMap(c=>c.default_facts))).map(key=>({key,label:labels[key]?.[0]??key,group:labels[key]?.[1]??"其他"})).filter(f=>`${f.label}${f.key}`.toLowerCase().includes(search.toLowerCase()));return Object.entries(facts.reduce<Record<string,typeof facts>>((o,f)=>{(o[f.group]??=[]).push(f);return o},{}))},[registry,search]);
 const toggle=(key:string)=>{if(chapter.required_facts.includes(key))return;setNotice("");onChange(value.includes(key)?value.filter(v=>v!==key):[...value,key])};
 return <div><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xl">{chapter.name}</h3><p className="text-xs" style={{color:"var(--ink-faint)"}}>已选 {value.length} 项；必需项由后端锁定。</p></div><button type="button" disabled={saving} onClick={async()=>{setSaving(true);setNotice("");try{const r=await resetPromptConfig(chapter.key);onChange(r.fact_keys);setNotice("已恢复默认配置")}catch{setNotice("恢复默认失败，请重试")}finally{setSaving(false)}}} className="btn-ghost flex items-center gap-1 px-3 py-2 text-sm disabled:opacity-40"><RotateCcw size={14}/>恢复默认</button></div>
 <label className="mt-4 flex items-center gap-2 border px-3 py-2" style={{borderColor:"var(--line)"}}><Search size={14}/><span className="sr-only">搜索前置数据</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索前置数据" className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></label>
 <div className="mt-4 grid max-h-[52vh] gap-x-8 gap-y-5 overflow-y-auto pr-2 md:grid-cols-2">{groups.map(([group,items])=><fieldset key={group}><legend className="mb-2 text-sm font-medium">{group}</legend>{items.map(f=>{const required=chapter.required_facts.includes(f.key);return <label key={f.key} className="flex cursor-pointer gap-2 border-t py-2 text-sm" style={{borderColor:"var(--line-soft)"}}><input type="checkbox" checked={value.includes(f.key)||required} disabled={required} onChange={()=>toggle(f.key)} className="mt-1 accent-amber-700"/><span>{f.label}{required&&<em className="ml-1 not-italic" style={{color:"var(--gold-deep)"}}><Check className="inline" size={12}/>必需</em>}<small className="block font-mono" style={{color:"var(--ink-faint)"}}>{f.key}</small></span></label>})}</fieldset>)}</div>
 <div className="mt-5 flex items-center justify-end gap-3"><span role="status" className="text-xs" style={{color:"var(--gold-deep)"}}>{notice}</span><button type="button" disabled={saving} onClick={async()=>{setSaving(true);setNotice("");try{const r=await savePromptConfig(chapter.key,value);onChange(r.fact_keys);setNotice("本章配置已保存")}catch{setNotice("保存失败，请重试")}finally{setSaving(false)}}} className="btn-gold flex items-center gap-2 px-4 py-2 text-sm disabled:opacity-50">{saving?<LoaderCircle className="animate-spin" size={14}/>:<Save size={14}/>}保存配置</button></div></div>
}
