"use client";
import { useMemo, useState } from "react";
import { Check, Clipboard, RotateCcw, Search, Settings2 } from "lucide-react";
import { chapterRequired, chapters, factOptions, type CalculationRecord } from "./data";

export function PromptWorkspace({record,locale="zh"}:{record:CalculationRecord;locale?:string}){
  const [activeKey,setActiveKey]=useState(chapters[0].key);const [search,setSearch]=useState("");const [copied,setCopied]=useState(false);
  const [selections,setSelections]=useState<Record<string,string[]>>(()=>Object.fromEntries(chapters.map(c=>[c.key,[...c.defaults]])));
  const chapter=chapters.find(c=>c.key===activeKey)!;const selected=selections[activeKey]??[];
  const groups=useMemo(()=>{const options=factOptions.filter(f=>`${f.label}${f.group}${f.key}`.toLowerCase().includes(search.toLowerCase()));const grouped=options.reduce<Record<string,typeof factOptions>>((all,f)=>{(all[f.group]??=[]).push(f);return all;},{});return Object.entries(grouped);},[search]);
  const toggle=(key:string)=>{if(chapterRequired[activeKey]?.includes(key))return;setSelections(s=>({...s,[activeKey]:selected.includes(key)?selected.filter(v=>v!==key):[...selected,key]}));};
  const reset=()=>setSelections(s=>({...s,[activeKey]:[...chapter.defaults]}));
  const prompt=`你是专业的八字命理解读者。只解释提供的确定性事实，不得重新排盘或修改任何干支、年份及算法结论。\n\n章节：${chapter.no}. ${chapter.title} (${chapter.key})\n任务：${chapter.purpose}\nlocale: ${locale}\n输出要求：所有标题与正文直接使用 locale 指定的语言，不经过二次翻译。\n事实哈希：${record.factsHash}\n允许使用的前置数据：${selected.join(", ")}\n\n请仅返回符合本章节 Schema 的严格 JSON。`;
  return <section className="min-w-0 border" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}>
    <header className="border-b px-5 py-4" style={{borderColor:"var(--line)"}}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs tracking-widest" style={{color:"var(--gold-deep)"}}>PROMPT COMPOSER · 10 CHAPTERS</p><h2 className="mt-1 text-xl">{record.name}</h2><p className="mt-1 text-xs" style={{color:"var(--ink-faint)"}}>计算版本 v{record.versions} · facts_hash {record.factsHash} · locale {locale}</p></div><div className="flex gap-2"><button type="button" className="btn-ghost px-3 py-2 text-sm">查看完整计算</button><button type="button" className="btn-gold px-3 py-2 text-sm">生成全部10章</button></div></div></header>
    <div className="grid min-h-[660px] xl:grid-cols-[13rem_minmax(0,1fr)_19rem]">
      <nav aria-label="报告章节" className="border-b xl:border-b-0 xl:border-r" style={{borderColor:"var(--line)"}}><div className="flex overflow-x-auto xl:block">{chapters.map(c=><button key={c.key} type="button" onClick={()=>setActiveKey(c.key)} aria-current={activeKey===c.key?"step":undefined} className="flex min-w-44 items-center gap-3 border-b px-4 py-3 text-left text-sm xl:w-full xl:min-w-0" style={{borderColor:"var(--line-soft)",background:activeKey===c.key?"var(--gold-soft)":"transparent"}}><span className="w-5 font-[var(--serif-d)]" style={{color:"var(--gold-deep)"}}>{String(c.no).padStart(2,"0")}</span><span><span className="block font-medium">{c.title}</span><span className="block truncate text-[10px]" style={{color:"var(--ink-faint)"}}>{c.key}</span></span></button>)}</div></nav>
      <div className="min-w-0 border-b p-5 xl:border-b-0 xl:border-r" style={{borderColor:"var(--line)"}}><div className="mb-5 flex items-start justify-between gap-3"><div><p className="text-xs" style={{color:"var(--gold-deep)"}}>第 {chapter.no} 章</p><h3 className="text-2xl">{chapter.title}</h3><p className="mt-1 text-sm" style={{color:"var(--ink-soft)"}}>{chapter.purpose}</p></div><span className="border px-2 py-1 text-xs" style={{borderColor:"var(--line)",color:"var(--ink-faint)"}}>full-report-v1</span></div><div className="mb-3 flex items-center justify-between"><h4 className="text-sm font-medium">最终调用指令</h4><button type="button" onClick={()=>{void navigator.clipboard?.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),1200);}} className="flex items-center gap-1 text-xs" style={{color:"var(--gold-deep)"}}>{copied?<Check size={14}/>:<Clipboard size={14}/>} {copied?"已复制":"复制"}</button></div><pre className="min-h-64 overflow-auto whitespace-pre-wrap border p-4 font-mono text-xs leading-6" style={{borderColor:"var(--line)",background:"var(--bg)",color:"var(--ink-soft)"}}>{prompt}</pre><details className="mt-4 border" style={{borderColor:"var(--line-soft)"}}><summary className="cursor-pointer px-4 py-3 text-sm">实际事实输入 JSON · {selected.length} 项</summary><pre className="max-h-56 overflow-auto border-t p-4 font-mono text-xs" style={{borderColor:"var(--line-soft)"}}>{JSON.stringify({facts_hash:record.factsHash,chapter_key:chapter.key,included_facts:selected.reduce((o,k)=>({...o,[k]:"<计算结果>"}),{})},null,2)}</pre></details><details className="mt-3 border" style={{borderColor:"var(--line-soft)"}}><summary className="cursor-pointer px-4 py-3 text-sm">输出 JSON Schema</summary><pre className="border-t p-4 font-mono text-xs" style={{borderColor:"var(--line-soft)"}}>{JSON.stringify({type:"object",required:["no","key","title","body"],properties:{no:{const:chapter.no},key:{const:chapter.key},title:{type:"string"},body:{type:"string"}}},null,2)}</pre></details></div>
      <aside className="p-4"><div className="flex items-center justify-between"><h3 className="flex items-center gap-2 text-base"><Settings2 size={16}/>前置数据配置</h3><button type="button" onClick={reset} className="flex items-center gap-1 text-xs" style={{color:"var(--gold-deep)"}}><RotateCcw size={13}/>恢复默认</button></div><p className="mt-1 text-xs" style={{color:"var(--ink-faint)"}}>当前选中 {selected.length} 项；锁定项为生成本章的必要数据。</p><label className="mt-3 flex items-center gap-2 border px-3 py-2"><Search size={14}/><span className="sr-only">搜索前置数据</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索数据项" className="min-w-0 flex-1 bg-transparent text-xs outline-none"/></label><div className="mt-4 max-h-[545px] space-y-5 overflow-y-auto pr-1">{groups.map(([group,items])=><fieldset key={group}><legend className="mb-2 text-xs font-medium" style={{color:"var(--ink-soft)"}}>{group}</legend><div className="space-y-1">{items.map(f=>{const required=chapterRequired[activeKey]?.includes(f.key);return <label key={f.key} className="flex cursor-pointer items-start gap-2 px-2 py-1.5 text-xs hover:bg-black/5"><input type="checkbox" checked={selected.includes(f.key)} disabled={required} onChange={()=>toggle(f.key)} className="mt-0.5 accent-amber-700"/><span><span className="block">{f.label}{required&&<em className="ml-1 not-italic" style={{color:"var(--gold-deep)"}}>必需</em>}</span><span className="font-mono text-[10px]" style={{color:"var(--ink-faint)"}}>{f.key}</span></span></label>})}</div></fieldset>)}</div></aside>
    </div>
  </section>;
}
