"use client";
import {useEffect,useMemo,useState} from "react";
import {Check,Clipboard,FileText,LoaderCircle,Settings2,X} from "lucide-react";
import {previewCalculationPrompt,type CalculationArchive,type CalculationVersion,type PromptPreviewResponse,type PromptRegistryResponse} from "@/lib/admin-api";
import {ChapterFactConfig} from "./ChapterFactConfig";

export function PromptWorkspace({archive,version,registry,locale,initialConfig}:{archive:CalculationArchive;version:CalculationVersion;registry:PromptRegistryResponse;locale:string;initialConfig:Record<string,string[]>}){
 const [active,setActive]=useState(registry.chapters[0]?.key??"");
 const [selected,setSelected]=useState<Record<string,string[]>>(()=>Object.fromEntries(registry.chapters.map(c=>[c.key,[...(initialConfig[c.key]??c.default_facts)]])));
 const [preview,setPreview]=useState<PromptPreviewResponse|null>(null);const [configOpen,setConfigOpen]=useState(false);const [factsOpen,setFactsOpen]=useState(false);const [view,setView]=useState<"chapter"|"additive"|"complete">("complete");const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [copied,setCopied]=useState(false);
 const chapter=registry.chapters.find(c=>c.key===active)??registry.chapters[0];const chosen=useMemo(()=>selected[chapter.key]??chapter.default_facts,[selected,chapter]);
 useEffect(()=>{let valid=true;setLoading(true);setError("");previewCalculationPrompt(archive.id,version.id,chapter.key,locale,chosen).then(v=>{if(valid)setPreview(v)}).catch(()=>{if(valid){setPreview(null);setError("Prompt 预览生成失败，请检查计算版本后重试。")}}).finally(()=>{if(valid)setLoading(false)});return()=>{valid=false}},[archive.id,version.id,chapter.key,locale,chosen]);
 const instruction=preview?(view==="chapter"?preview.chapter_instruction:view==="additive"?preview.additive_instruction:preview.complete_instruction):"";
 const copy=async()=>{if(!instruction)return;await navigator.clipboard?.writeText(instruction);setCopied(true);setTimeout(()=>setCopied(false),1200)};
 return <section className="min-w-0 border" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}>
  <header className="border-b px-5 py-4" style={{borderColor:"var(--line)"}}><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs tracking-widest" style={{color:"var(--gold-deep)"}}>十章提示词编排</p><h2 className="mt-1 text-xl">{archive.name}</h2><p className="mt-1 text-xs" style={{color:"var(--ink-faint)"}}>计算版本 v{version.version_no} · 事实哈希 {version.facts_hash} · 语言 {registry.locales.find(item=>item.code===locale)?.name??locale}</p></div><div className="flex items-center gap-2"><button type="button" onClick={()=>setConfigOpen(true)} className="btn-ghost flex items-center gap-2 px-3 py-2 text-sm"><Settings2 size={15}/>查看前置数据配置</button><p className="border px-3 py-2 text-xs" style={{borderColor:"var(--line)"}}>仅预览，暂不生成解读</p></div></div></header>
  <div className="grid min-h-[660px] xl:grid-cols-[13rem_minmax(0,1fr)]"><nav aria-label="报告章节" className="border-b xl:border-b-0 xl:border-r" style={{borderColor:"var(--line)"}}><div className="flex overflow-x-auto xl:block">{registry.chapters.map(c=><button key={c.key} type="button" onClick={()=>setActive(c.key)} aria-current={chapter.key===c.key?"step":undefined} className="flex min-w-44 items-center gap-3 border-b px-4 py-3 text-left text-sm xl:w-full xl:min-w-0" style={{borderColor:"var(--line-soft)",background:chapter.key===c.key?"var(--gold-soft)":"transparent"}}><span style={{color:"var(--gold-deep)"}}>{String(c.no).padStart(2,"0")}</span><b className="font-medium">{c.name}</b></button>)}</div></nav>
   <main className="min-w-0 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs" style={{color:"var(--gold-deep)"}}>第 {chapter.no} 章</p><h3 className="text-2xl">{chapter.name}</h3><p className="mt-1 text-sm" style={{color:"var(--ink-soft)"}}>{chapter.purpose}</p></div><div className="text-right"><p className="text-xs" style={{color:"var(--ink-faint)"}}>固定模块顺序</p><p className="mt-1 text-sm">{chapter.sections.map(s=>s.name).join(" · ")}</p></div></div>
    <div className="mb-3 mt-5 flex flex-wrap items-center justify-between gap-3"><div><h4 className="flex items-center gap-2 text-sm font-medium"><FileText size={15}/>指令预览</h4><p className="mt-1 text-xs" style={{color:"var(--ink-faint)"}}>已代入本章前置数据 · 当前指令 {instruction.length} 字符</p></div><div className="flex items-center gap-3"><button type="button" onClick={()=>setFactsOpen(true)} disabled={!preview} className="btn-ghost px-3 py-2 text-xs disabled:opacity-40">查看本章代入数据</button><button type="button" onClick={copy} disabled={!instruction} className="flex items-center gap-1 text-xs disabled:opacity-40" style={{color:"var(--gold-deep)"}}>{copied?<Check size={14}/>:<Clipboard size={14}/>} {copied?"已复制":"复制当前指令"}</button></div></div>
    <div role="tablist" aria-label="指令预览类型" className="mb-3 flex border-b" style={{borderColor:"var(--line)"}}>{([['chapter','章节基础指令'],['additive','语言附加指令'],['complete','最终完整指令']] as const).map(([key,label])=><button key={key} type="button" role="tab" aria-selected={view===key} onClick={()=>setView(key)} className="border-b-2 px-4 py-2 text-sm" style={{borderColor:view===key?"var(--gold-deep)":"transparent",color:view===key?"var(--gold-deep)":"var(--ink-soft)"}}>{label}</button>)}</div>
    {loading?<div className="flex min-h-80 items-center justify-center border text-sm" style={{borderColor:"var(--line)"}}><LoaderCircle className="mr-2 animate-spin" size={16}/>正在整理并代入本章前置数据</div>:error?<div role="alert" className="min-h-80 border p-4 text-sm text-red-800" style={{borderColor:"var(--line)"}}>{error}</div>:<section><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><h5 className="text-xs" style={{color:"var(--ink-faint)"}}>{view==="chapter"?"本章规则与实际前置数据":view==="additive"?"目标语言、专业术语与一致性要求":"实际提交时使用的完整内容"}</h5><span className="text-xs" style={{color:"var(--gold-deep)"}}>{view==="complete"?"基础指令＋语言附加指令＋JSON输出协议":""}</span></div><pre role="tabpanel" className="max-h-[40rem] overflow-auto whitespace-pre-wrap border p-5 font-sans text-sm leading-7" style={{borderColor:"var(--line)",background:"var(--bg)"}}>{instruction}</pre>{preview?.semantic_digest.warnings?.length?<div role="alert" className="mt-3 border px-4 py-3 text-sm text-amber-900" style={{borderColor:"var(--line)"}}>数据整理提示：{preview.semantic_digest.warnings.join("；")}</div>:null}</section>}
    <details className="mt-4 border" style={{borderColor:"var(--line-soft)"}}><summary className="cursor-pointer px-4 py-3 text-sm">原始事实数据 · {chosen.length} 项</summary><pre className="max-h-64 overflow-auto border-t p-4 font-mono text-xs">{JSON.stringify(preview?.input_facts??{},null,2)}</pre></details><details className="mt-3 border" style={{borderColor:"var(--line-soft)"}}><summary className="cursor-pointer px-4 py-3 text-sm">程序接收结构（技术预览）</summary><pre className="max-h-64 overflow-auto border-t p-4 font-mono text-xs">{JSON.stringify(preview?.output_schema??{},null,2)}</pre></details>
   </main></div>
  {configOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setConfigOpen(false)}}><section role="dialog" aria-modal="true" aria-labelledby="fact-config-title" className="w-full max-w-4xl border p-5 shadow-2xl" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}><header className="mb-5 flex items-start justify-between border-b pb-4" style={{borderColor:"var(--line)"}}><div><h2 id="fact-config-title" className="text-2xl">章节事实配置</h2><p className="mt-1 text-sm" style={{color:"var(--ink-soft)"}}>与“基础数据 → 章节事实配置”使用同一份后端配置。</p></div><button autoFocus type="button" onClick={()=>setConfigOpen(false)} aria-label="关闭章节事实配置" className="btn-ghost p-2"><X size={18}/></button></header><ChapterFactConfig registry={registry} activeKey={chapter.key} value={chosen} onChange={keys=>setSelected(s=>({...s,[chapter.key]:keys}))}/></section></div>}
  {factsOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setFactsOpen(false)}}><section role="dialog" aria-modal="true" aria-labelledby="injected-facts-title" className="w-full max-w-3xl border p-5 shadow-2xl" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}><header className="mb-4 flex items-start justify-between border-b pb-4" style={{borderColor:"var(--line)"}}><div><h2 id="injected-facts-title" className="text-2xl">本章代入数据</h2><p className="mt-1 text-sm" style={{color:"var(--ink-soft)"}}>以下为系统从完整计算快照中整理后，实际写入本章指令的可读数据。</p></div><button autoFocus type="button" onClick={()=>setFactsOpen(false)} aria-label="关闭本章代入数据" className="btn-ghost p-2"><X size={18}/></button></header><ul className="max-h-[60vh] space-y-2 overflow-auto">{preview?.semantic_digest?.items?.filter(item=>item.status==="available").map(item=><li key={`${item.fact}-${item.text}`} className="border px-4 py-3 text-sm leading-6" style={{borderColor:"var(--line-soft)",background:"var(--bg)"}}>{item.text}</li>)}</ul></section></div>}
 </section>
}
