"use client";
import { useEffect, useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { ChevronLeft, ChevronRight, History, Trash2, X } from "lucide-react";
import type { ChartRecord } from "./types";
type Translate = (key: string, values?: Record<string, number>) => string;

export function HistoryDialog({open,onOpenChange,records,total,page,pageSize,loading,onPageChange,onDelete,onView,t}:{open:boolean;onOpenChange:(v:boolean)=>void;records:ChartRecord[];total:number;page:number;pageSize:number;loading:boolean;onPageChange:(p:number)=>void;onDelete:(ids:number[])=>void;onView:(r:ChartRecord)=>void;t:Translate}){
 const [selected,setSelected]=useState<Set<number>>(new Set());
 const totalPages=Math.max(1,Math.ceil(total/pageSize));
 const allSelected=records.length>0&&records.every(r=>selected.has(r.id));
 useEffect(()=>setSelected(new Set()),[open,page]);
 const togglePage=()=>setSelected(current=>{const next=new Set(current);records.forEach(r=>allSelected?next.delete(r.id):next.add(r.id));return next});
 const remove=(ids:number[])=>{if(!window.confirm(t(ids.length>1?"confirmBatchDelete":"confirmDelete",{count:ids.length})))return;onDelete(ids);setSelected(new Set())};
 return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-[#21170d]/55 backdrop-blur-[2px]"/><Dialog.Content className="fixed left-1/2 top-1/2 z-40 flex max-h-[90vh] w-[calc(100%-2rem)] max-w-[1080px] -translate-x-1/2 -translate-y-1/2 flex-col border border-[var(--line)] bg-[var(--bg-card)] shadow-2xl focus:outline-none">
  <div className="flex items-start justify-between border-b border-[var(--line)] px-5 py-5 sm:px-8"><div><div className="mb-2 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[.2em] text-[var(--gold-deep)]"><History className="h-4 w-4"/>{t("historyEyebrow")}</div><Dialog.Title className="font-[var(--serif)] text-2xl font-semibold text-[var(--ink)]">{t("historyTitle")}</Dialog.Title><Dialog.Description className="mt-2 text-xs text-[var(--ink-faint)]">{t("historyCount",{count:total})}</Dialog.Description></div><Dialog.Close className="grid h-10 w-10 place-items-center border border-[var(--line)]" aria-label={t("close")}><X className="h-4 w-4"/></Dialog.Close></div>
  <div className="flex min-h-0 flex-1 flex-col overflow-hidden px-5 py-5 sm:px-8">{loading?<div className="grid min-h-72 place-items-center text-sm text-[var(--ink-faint)]">{t("historyLoading")}</div>:records.length===0?<div className="grid min-h-72 place-items-center border border-dashed border-[var(--line)] text-center"><div><History className="mx-auto mb-4 h-7 w-7 text-[var(--gold-deep)]"/><h3 className="font-[var(--serif)] text-lg">{t("historyEmpty")}</h3><p className="mt-2 text-xs text-[var(--ink-faint)]">{t("historyEmptyHint")}</p></div></div>:<>
   <div className="mb-4 flex min-h-10 flex-wrap items-center justify-between gap-3 border-b border-[var(--line-soft)] pb-4"><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={allSelected} onChange={togglePage} className="h-4 w-4 accent-[var(--gold-deep)]"/>{t("selectPage")}</label>{selected.size>0&&<button type="button" onClick={()=>remove(Array.from(selected))} className="inline-flex min-h-9 items-center gap-2 border border-[#a95643]/45 px-3 text-xs text-[#8d3f31]"><Trash2 className="h-3.5 w-3.5"/>{t("batchDelete",{count:selected.size})}</button>}</div>
   <div className="min-h-0 flex-1 overflow-y-auto pr-1"><ul className="space-y-3" aria-label={t("historyTitle")}>{records.map(record=><li key={record.id} className="grid gap-4 border border-[var(--line)] bg-[var(--bg)] p-4 sm:grid-cols-[auto_minmax(0,1fr)_auto] sm:items-center sm:p-5"><input type="checkbox" checked={selected.has(record.id)} onChange={()=>setSelected(current=>{const next=new Set(current);if(next.has(record.id))next.delete(record.id);else next.add(record.id);return next})} className="h-4 w-4 accent-[var(--gold-deep)]" aria-label={t("selectRecord")}/><button type="button" onClick={()=>onView(record)} className="min-w-0 text-left"><div className="flex flex-wrap items-baseline gap-x-4 gap-y-1"><strong className="font-[var(--serif)] text-base">{record.solarDate}</strong><span className="text-xs text-[var(--gold-deep)]">{record.pillars.map(p=>`${p.stem}${p.branch}`).join(" · ")}</span></div><div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-xs text-[var(--ink-faint)]"><span>{record.gender===1?t("male"):t("female")}</span><span>{record.place}</span><span>{record.coordinates}</span><span>{record.createdAt}</span></div></button><div className="flex gap-2"><button type="button" onClick={()=>onView(record)} className="min-h-9 border border-[var(--gold)] px-4 text-xs text-[var(--gold-deep)]">{t("view")}</button><button type="button" onClick={()=>remove([record.id])} className="grid h-9 w-9 place-items-center border border-[var(--line)]" aria-label={t("delete")}><Trash2 className="h-3.5 w-3.5"/></button></div></li>)}</ul></div>
   <nav className="mt-5 flex items-center justify-between border-t border-[var(--line-soft)] pt-4" aria-label={t("pagination")}><span className="text-xs text-[var(--ink-faint)]">{t("pageStatus",{page,total:totalPages})}</span><div className="flex items-center gap-2"><button type="button" disabled={page===1} onClick={()=>onPageChange(page-1)} className="grid h-9 w-9 place-items-center border border-[var(--line)] disabled:opacity-35" aria-label={t("previousPage")}><ChevronLeft className="h-4 w-4"/></button>{Array.from({length:totalPages},(_,i)=>i+1).map(n=><button key={n} type="button" onClick={()=>onPageChange(n)} aria-current={page===n?"page":undefined} className={`h-9 min-w-9 border px-2 text-xs ${page===n?"border-[var(--gold-deep)] bg-[var(--gold-deep)] text-[var(--bg-card)]":"border-[var(--line)]"}`}>{n}</button>)}<button type="button" disabled={page===totalPages} onClick={()=>onPageChange(page+1)} className="grid h-9 w-9 place-items-center border border-[var(--line)] disabled:opacity-35" aria-label={t("nextPage")}><ChevronRight className="h-4 w-4"/></button></div></nav>
  </>}</div>
 </Dialog.Content></Dialog.Portal></Dialog.Root>
}
