"use client";
import Link from "next/link";
import {useEffect,useMemo,useRef,useState} from "react";
import {ArrowLeft,Braces,RotateCcw,X} from "lucide-react";
import {CalculationArchive,CalculationVersion,fetchCalculation,recalculateCalculation} from "@/lib/admin-api";
import {displayCode,displayCoordinates,displayDateTime,displayNumber,displayUTCOffset} from "@/lib/bazi-display";
type Obj=Record<string,unknown>;type Row=[string,unknown];
const object=(v:unknown):Obj=>v&&typeof v==="object"&&!Array.isArray(v)?v as Obj:{};
const path=(v:unknown,...keys:string[])=>keys.reduce<unknown>((current,key)=>object(current)[key],v);
const first=(...values:unknown[])=>values.find(v=>v!==undefined&&v!==null&&v!=="");
const text=displayCode;
const num=(v:unknown,d=2)=>typeof v==="number"?displayNumber(v,d):text(v);
const element=(value:unknown)=>displayCode(value);
const level=displayCode;
const gender=(v:unknown)=>Number(v)===1?"乾 · 男":"坤 · 女";
const pillar=(chart:Obj,key:string)=>object(first(path(chart,"data","pillars",key),path(chart,"pillars",key)));
const ganZhi=(p:Obj)=>`${text(p.stem)==="—"?"":text(p.stem)}${text(p.branch)==="—"?"":text(p.branch)}`||"—";
const relations=(items:unknown)=>Array.isArray(items)?items.map(item=>{const row=object(item),symbols=Array.isArray(row.symbols)?row.symbols.join("、"):"",kind=displayCode(first(row.type,row.code));return [symbols,kind].filter(v=>v&&v!=="—").join(" · ")||displayCode(first(row.name,row.reason))}).filter(Boolean).join("；"):"—";
const percent=(v:unknown)=>typeof v==="number"?`${displayNumber(v<=1?v*100:v,2)}%`:text(v);
const grade=(v:unknown)=>{const n=Number(v);if(!Number.isFinite(n))return "—";return `${displayNumber(n,2)} · ${n<30?"偏弱":n<50?"一般":n<70?"偏强":"很强"}`};
const relationItems=(items:unknown,type:"growth"|"normal")=>Array.isArray(items)?items.filter(item=>(String(object(item).type)==="long_life") === (type==="growth")):[];
const nonEmptyList=(...values:unknown[])=>values.find(value=>Array.isArray(value)?value.length>0:value!==undefined&&value!==null&&value!=="");
function Rows({rows}:{rows:Row[]}){return <dl>{rows.map(([label,value])=><div key={label} className="grid grid-cols-[8rem_1fr] gap-3 border-t py-2.5 text-sm first:border-t-0" style={{borderColor:"var(--line-soft)"}}><dt style={{color:"var(--ink-faint)"}}>{label}</dt><dd className="m-0 break-words">{text(value)}</dd></div>)}</dl>}
function Card({title,rows,children}:{title:string;rows?:Row[];children?:React.ReactNode}){return <article className="border-t-2 p-5" style={{borderColor:"var(--gold)",background:"var(--bg-card)"}}><h3 className="mb-3 text-base font-semibold">{title}</h3>{rows&&<Rows rows={rows}/>} {children}</article>}
function LogicPanel({title,children}:{title:string;children:React.ReactNode}){
 const[open,setOpen]=useState(false);
 const dialog=useRef<HTMLElement>(null);
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false);if(event.key==="Tab"&&dialog.current){const nodes=Array.from(dialog.current.querySelectorAll<HTMLElement>('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')).filter(node=>!node.hasAttribute("disabled"));if(nodes.length===0)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};window.addEventListener("keydown",close);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",close)}},[open]);
 return <div className="mt-4 border-t pt-4" style={{borderColor:"var(--line-soft)"}}><button type="button" onClick={()=>setOpen(true)} className="btn-ghost px-4 py-2 text-sm">查看{title}计算逻辑</button>{open&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/55 p-4" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false)}}><section ref={dialog} role="dialog" aria-modal="true" aria-labelledby="logic-dialog-title" className="flex max-h-[88vh] w-full max-w-5xl flex-col border shadow-2xl" style={{borderColor:"var(--gold)",background:"var(--bg-card)"}}><header className="flex items-start justify-between gap-4 border-b px-5 py-4" style={{borderColor:"var(--line)"}}><div><p className="text-xs tracking-[.18em]" style={{color:"var(--gold-deep)"}}>计算逻辑</p><h3 id="logic-dialog-title" className="mt-1 text-xl">{title}计算逻辑</h3><p className="mt-1 text-xs" style={{color:"var(--ink-faint)"}}>展示本计算版本实际使用的规则、数据和逐步判断。</p></div><button type="button" autoFocus aria-label="关闭计算逻辑" onClick={()=>setOpen(false)} className="btn-ghost grid h-10 w-10 place-items-center"><X size={18}/></button></header><div className="space-y-5 overflow-y-auto p-5 sm:p-6">{children}</div></section></div>}</div>
}
function TraceList({items}:{items:unknown}){if(!Array.isArray(items)||items.length===0)return <p className="text-sm" style={{color:"var(--ink-faint)"}}>当前快照没有逐步明细。</p>;return <ol className="space-y-2">{items.map((item,index)=>{const row=object(item),detail=first(row.reason,row.rejected_by,row.evidence);return <li key={index} className="border-b pb-2 text-sm" style={{borderColor:"var(--line-soft)"}}><b>{index+1}. {displayCode(first(row.result,row.type,row.rule))}</b>{row.matched!==undefined&&<span> · {row.matched?"命中":"未命中"}</span>}{row.score!==undefined&&<span> · {num(row.score)}分</span>}<div className="mt-1 text-xs" style={{color:"var(--ink-soft)"}}>{displayCode(detail)}</div></li>})}</ol>}
export default function Page({params}:{params:{id:string}}){
 const[archive,setArchive]=useState<CalculationArchive|null>(null),[versions,setVersions]=useState<CalculationVersion[]>([]),[selected,setSelected]=useState<CalculationVersion|null>(null),[tab,setTab]=useState("overview"),[rawOpen,setRawOpen]=useState(false),[error,setError]=useState("");
 const load=async()=>{try{const r=await fetchCalculation(params.id);setArchive(r.archive);setVersions(r.versions);setSelected(v=>v&&r.versions.find(x=>x.id===v.id)||r.versions[0]||null)}catch{setError("计算档案读取失败")}};
 useEffect(()=>{void load()},[params.id]);
 const view=useMemo(()=>{if(!archive||!selected)return null;const input=object(selected.input_snapshot),time=object(selected.time_calculation_snapshot),chart=object(selected.chart_snapshot),facts=object(selected.facts_snapshot),location=object(first(archive.input.location,input.location,path(facts,"input","location"))),strength=object(first(path(facts,"day_master_strength","analysis_v2"),path(chart,"data","strength_v2"),path(chart,"strength_v2"),path(facts,"day_master_strength"))),legacy=object(first(path(chart,"data","strength"),path(chart,"strength"))),tenGod=object(first(path(chart,"data","ten_god_analysis"),path(chart,"data","ten_god_effective"),path(facts,"ten_god_analysis"))),useful=object(first(path(facts,"useful_god"),path(chart,"data","useful_god"))),power=object(first(path(chart,"data","element_power","effective_ratio"),path(chart,"data","element_power","effective_power"))),annualRange=object(first(path(chart,"data","annual_fortune_range"),path(facts,"chart","data","annual_fortune_range")));return{input,time,chart,facts,location,strength,legacy,tenGod,useful,power,annualRange}},[archive,selected]);
 if(error)return <p role="alert">{error}</p>;if(!archive||!selected||!view)return <p>正在读取完整计算链路…</p>;
 const{input,time,chart,facts,location,strength,legacy,tenGod,useful,power,annualRange}=view;
 const pillars=[["年柱",pillar(chart,"year")],["月柱",pillar(chart,"month")],["日柱",pillar(chart,"day")],["时柱",pillar(chart,"hour")]] as const;
 const tabs=[["overview","总览"],["power","五行与强弱"],["relations","十神与关系"],["fortune","喜用神与运势"],["trace","计算追溯"]];
 const birth=`${text(input.year)}年${text(input.month)}月${text(input.day)}日 ${String(first(input.hour,0)).padStart(2,"0")}:${String(first(input.minute,0)).padStart(2,"0")}`;
 const longitude=first(input.longitude,location.longitude,path(facts,"input","longitude")),latitude=first(input.latitude,location.latitude,path(facts,"input","latitude"));
 const place=first(location.display_name,[location.country_name,location.region_name||location.city].filter(Boolean).join(" / "),archive.input.location.display_name,"经纬度输入");
 const strengthLevel=level(first(strength.level,legacy.level,path(facts,"day_master_strength","level"))),score=first(strength.score,legacy.score,path(facts,"day_master_strength","score")),confidence=first(strength.confidence,path(facts,"day_master_strength","confidence"));
 return <section><Link href="/admin/report-workspace/calculations" className="mb-4 inline-flex gap-1 text-sm"><ArrowLeft size={15}/>返回计算档案</Link><div className="border" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}>
  <header className="flex flex-wrap justify-between gap-5 border-b p-6" style={{borderColor:"var(--line)"}}><div><p className="text-xs tracking-[.2em]" style={{color:"var(--gold-deep)"}}>计算追溯</p><h2 className="mt-1 text-2xl">{archive.name}</h2><p className="mt-1 text-sm" style={{color:"var(--ink-faint)"}}>{birth} · {gender(input.gender)} · {text(place)}</p></div><div className="flex flex-wrap items-start gap-2"><select aria-label="计算版本" value={selected.id} onChange={e=>setSelected(versions.find(v=>v.id===Number(e.target.value))||selected)} className="border bg-[var(--bg-card)] px-3 py-2 text-sm" style={{borderColor:"var(--line)"}}>{versions.map(v=><option key={v.id} value={v.id}>第 {v.version_no} 版 · {new Date(v.created_at).toLocaleString("zh-CN")}</option>)}</select><Link className="btn-gold px-4 py-2 text-sm" href={`/admin/report-workspace/prompts?calculation_id=${archive.id}`}>用于 Prompt 编排</Link><button className="btn-ghost flex gap-1 px-4 py-2 text-sm" onClick={async()=>{await recalculateCalculation(archive.id);await load()}}><RotateCcw size={15}/>重新计算</button></div></header>
  <div className="grid border-b sm:grid-cols-4" style={{borderColor:"var(--line)"}}>{([["出生记录时区",first(time.timezone_id,input.timezone_id,location.timezone_id)],["真太阳时",displayDateTime(first(time.true_solar_time,time.apparent_solar_time))],["身强弱",`${strengthLevel}${score!==undefined?` · ${num(score)}分`:""}`],["当前版本",`第 ${selected.version_no} 版 · 计算完成`]] as Row[]).map(([label,value])=><div key={label} className="border-r p-4 last:border-r-0" style={{borderColor:"var(--line-soft)"}}><div className="text-xs" style={{color:"var(--ink-faint)"}}>{label}</div><div className="mt-1 text-sm">{text(value)}</div></div>)}</div>
  <div className="grid border-b sm:grid-cols-4" style={{borderColor:"var(--line)"}}>{pillars.map(([label,p])=><div key={label} className="border-r p-5 text-center last:border-r-0" style={{borderColor:"var(--line-soft)"}}><div className="text-xs" style={{color:"var(--ink-faint)"}}>{label}</div><strong className="mx-auto my-3 block w-14 border px-2 py-3 text-2xl font-medium leading-tight" style={{borderColor:"var(--gold)"}}>{ganZhi(p).split("").map((x,i)=><span className="block" key={`${x}${i}`}>{x}</span>)}</strong><small style={{color:"var(--ink-faint)"}}>{element(p.stem_element)} · {element(p.branch_element)}{p.nayin?`｜${text(p.nayin)}`:""}</small></div>)}</div>
  <nav className="flex overflow-x-auto border-b px-5" style={{borderColor:"var(--line)"}}>{tabs.map(([key,label])=><button key={key} onClick={()=>setTab(key)} className="whitespace-nowrap border-b-2 px-4 py-4 text-sm" style={{borderColor:tab===key?"var(--gold-deep)":"transparent",color:tab===key?"var(--gold-deep)":"var(--ink-soft)"}}>{label}</button>)}</nav>
  <div className="p-5 sm:p-6">
   {tab==="overview"&&<div className="grid gap-4 xl:grid-cols-2"><Card title="输入资料" rows={[["历法",Number(input.calendar_type)===1?`农历${input.is_leap_month?" · 闰月":""}`:"公历"],["出生时间",birth],["出生地点",place],["经纬度",displayCoordinates(longitude,latitude)],["性别",gender(input.gender)]]}/><Card title="时间换算" rows={[["出生记录时区",first(time.timezone_id,input.timezone_id,location.timezone_id)],["当地钟表时间",displayDateTime(first(time.local_civil_time,time.local_standard_time))],["历史 UTC 偏移",displayUTCOffset(first(time.historical_utc_offset_seconds,time.standard_utc_offset_seconds))],["经度校正（分钟）",time.longitude_correction_minutes],["均时差（分钟）",time.equation_of_time_minutes],["真太阳时",displayDateTime(first(time.true_solar_time,time.apparent_solar_time))],["换日规则",time.day_boundary_rule],["是否跨日",time.crossed_date_boundary]]}/><Card title="命盘摘要" rows={[["四柱",pillars.map(([,p])=>ganZhi(p)).join(" · ")],["日主",first(path(chart,"data","day_master","stem"),path(chart,"day_master","stem"))],["生肖",first(path(chart,"data","meta","zodiac"),path(chart,"zodiac"))],["天干关系",relations(facts.stem_relations)],["地支合冲刑害",relations(relationItems(facts.branch_relations,"normal"))],["十二长生",relations(relationItems(facts.branch_relations,"growth"))]]}/><Card title="核心判断" rows={[["身强弱",strengthLevel],["综合评分",score],["可信度",percent(confidence)],["得令",grade(strength.de_ling)],["得地",grade(strength.de_di)],["得势",grade(strength.de_shi)],["首选用神",useful.primary?element(useful.primary):"当前规则未能确定"],["次选用神",useful.secondary?element(useful.secondary):"当前规则未能确定"]]}><p className="mt-3 border-l-2 px-3 text-xs leading-6" style={{borderColor:"var(--gold)",color:"var(--ink-soft)"}}>依据扶助与克泄耗力量、得令得地得势、五行有效力量及格局规则综合计算。</p></Card></div>}
   {tab==="power"&&<div className="grid gap-4 xl:grid-cols-2"><Card title="五行有效力量" rows={[["木",power.wood],["火",power.fire],["土",power.earth],["金",power.metal],["水",power.water]]}/><Card title="身强身弱" rows={[["结论",strengthLevel],["基础分",strength.base_score],["综合分",score],["扶助力量",first(strength.support,path(legacy,"analysis","support_score"))],["克泄耗力量",first(strength.pressure,path(legacy,"analysis","restraint_score"))],["扶助比例",percent(first(strength.support_ratio,path(legacy,"analysis","support_ratio")))],["根气力量",strength.root_power],["得令",grade(strength.de_ling)],["得地",grade(strength.de_di)],["得势",grade(strength.de_shi)],["可信度",percent(confidence)]]}><LogicPanel title="身强身弱"><Rows rows={[["算法版本",strength.rule_version],["基础公式","100 ×（扶助力量－克泄耗力量）÷（扶助力量＋克泄耗力量）"],["稳定修正","基础分×70%＋得令修正×10%＋得地修正×12%＋得势修正×8%"],["最终区间",`${num(score)}分 → ${strengthLevel}`]]}/><h4 className="font-semibold">逐步计算记录</h4><TraceList items={strength.trace}/><h4 className="font-semibold">格局候选</h4><TraceList items={strength.patterns}/></LogicPanel></Card></div>}
   {tab==="relations"&&<div className="grid gap-4 xl:grid-cols-2"><Card title="十神结构" rows={[["主要十神",tenGod.dominant_gods],["次要十神",tenGod.secondary_gods],["显现十神",tenGod.visible_gods],["有根十神",tenGod.rooted_gods],["缺失十神",tenGod.missing_gods],["集中度",percent(tenGod.concentration)]]}/><Card title="干支合冲刑害" rows={[["天干关系",relations(facts.stem_relations)],["地支关系",relations(relationItems(facts.branch_relations,"normal"))],["规则命中数",Array.isArray(facts.rule_matches)?facts.rule_matches.length:0]]}/><Card title="十二长生" rows={[["各柱状态",relations(relationItems(facts.branch_relations,"growth"))]]}/><Card title="计算提示" rows={[["提示信息",first(facts.warnings,"无")]]}/></div>}
   {tab==="fortune"&&<div className="grid gap-4 xl:grid-cols-2"><Card title="喜用神判断" rows={[["判断状态",useful.primary?"已确定":"待复核"],["首选用神",useful.primary?element(useful.primary):"当前规则未能确定"],["次选用神",useful.secondary?element(useful.secondary):"当前规则未能确定"],["正向候选元素",Array.isArray(useful.favorable)?useful.favorable.map(element):useful.favorable],["忌神",Array.isArray(useful.taboo)?useful.taboo.map(element):useful.taboo],["仇神",Array.isArray(useful.enemy)?useful.enemy.map(element):useful.enemy],["中性",Array.isArray(useful.neutral)?useful.neutral.map(element):useful.neutral],["可信度",percent(useful.confidence)]]}><p className="mt-3 border-l-2 px-3 text-xs leading-6" style={{borderColor:"var(--gold)",color:"var(--ink-soft)"}}>{useful.primary?"已根据候选评分与模拟结果选出主用神。":"没有元素同时满足有效、正向边际收益和处理主要病点三项条件，因此本版本保留为待复核，不强行给出用神。"}</p><LogicPanel title="喜用神"><Rows rows={[["算法版本",useful.rule_version],["当前状态",useful.primary?"已确定":"待复核"],["主用神筛选","候选有效、总分为正、边际收益为正，并满足主要病点处理条件"],["次用神筛选","主用神已确定、得分超过阈值、边际收益为正，且与主用神协同"],["校准提示",useful.warnings]]}/><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b" style={{borderColor:"var(--line)"}}>{["元素","角色","总分","可信度","有效","处理主病","边际收益","入选/淘汰原因"].map(x=><th className="px-2 py-2 font-medium" key={x}>{x}</th>)}</tr></thead><tbody>{Array.isArray(useful.candidates)&&useful.candidates.map((candidate,index)=>{const c=object(candidate),breakdown=object(c.breakdown);return <tr className="border-b align-top" style={{borderColor:"var(--line-soft)"}} key={index}><td className="px-2 py-2">{element(c.element)}</td><td className="px-2 py-2">{displayCode(c.role)}</td><td className="px-2 py-2">{num(c.score)}</td><td className="px-2 py-2">{percent(c.confidence)}</td><td className="px-2 py-2">{displayCode(c.valid)}</td><td className="px-2 py-2">{c.primary_required?displayCode(c.resolves_primary):"无需"}</td><td className="px-2 py-2">{num(breakdown.marginal_utility)}</td><td className="px-2 py-2">{displayCode(nonEmptyList(c.reject_reasons,c.reasons))}</td></tr>})}</tbody></table></div></LogicPanel></Card><Card title="大运与流年" rows={[["大运数量",Array.isArray(facts.luck_cycles)?facts.luck_cycles.length:0],["流年数量",Array.isArray(facts.annual_fortunes)?facts.annual_fortunes.length:0],["大运",Array.isArray(facts.luck_cycles)?facts.luck_cycles.map(item=>object(item).ganzhi).filter(Boolean):"—"],["流年范围",Array.isArray(facts.annual_fortunes)&&facts.annual_fortunes.length?`${text(object(facts.annual_fortunes[0]).year)}—${text(object(facts.annual_fortunes[facts.annual_fortunes.length-1]).year)}`:"—"],["截取规则",annualRange.selection_rule],["公共数据来源",annualRange.source],["日历版本",annualRange.data_version]]}/></div>}
   {tab==="trace"&&<div><div className="grid gap-4 xl:grid-cols-2"><Card title="计算版本" rows={[["历法库",path(facts,"versions","lunar_go_version")],["地点数据库",path(facts,"versions","location_database_version")],["时区数据库",path(facts,"versions","timezone_database_version")],["身强规则",first(path(facts,"versions","strength_v2_rule_version"),strength.rule_version)],["十神规则",first(path(facts,"versions","ten_god_effective_version"),tenGod.rule_version)],["喜用神规则",first(path(facts,"versions","useful_god_rule_version"),useful.rule_version)]]}/><Card title="数据指纹" rows={[["命盘指纹",selected.chart_hash],["事实指纹",selected.facts_hash],["档案版本",`第 ${selected.version_no} 版`],["生成时间",new Date(selected.created_at).toLocaleString("zh-CN")]]}/></div><button onClick={()=>setRawOpen(v=>!v)} className="btn-ghost mt-4 inline-flex items-center gap-2 px-4 py-2 text-sm"><Braces size={15}/>{rawOpen?"收起开发排查数据":"查看开发排查数据"}</button>{rawOpen&&<div className="mt-4 grid gap-4 xl:grid-cols-2">{[["输入资料",input],["时间换算",time],["四柱与基础计算",chart],["完整前置事实",facts]].map(([title,value])=><details open className="border" style={{borderColor:"var(--line)"}} key={title as string}><summary className="cursor-pointer px-4 py-3">{title as string}</summary><pre className="max-h-[30rem] overflow-auto border-t p-4 text-xs leading-6" style={{borderColor:"var(--line-soft)",background:"var(--bg)"}}>{JSON.stringify(value,null,2)}</pre></details>)}</div>}</div>}
  </div>
 </div></section>
}
