"use client";

import { createLLMProvider, fetchLLMCatalog, fetchLLMProviders, updateLLMProvider, type LLMProviderConfig, type LLMProviderPreset } from "@/lib/admin-api";
import { KeyRound, Plus, Search, Server } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type Form={code:string;name:string;base_url:string;api_key:string;enabled:boolean};
const emptyForm:Form={code:"",name:"",base_url:"",api_key:"",enabled:true};

export default function ProvidersPage(){
 const [rows,setRows]=useState<LLMProviderConfig[]>([]),[catalog,setCatalog]=useState<LLMProviderPreset[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState<LLMProviderConfig|null>(null),[form,setForm]=useState<Form>(emptyForm),[presetCode,setPresetCode]=useState(""),[created,setCreated]=useState<LLMProviderConfig|null>(null),[saving,setSaving]=useState(false);
 const pages=Math.max(1,Math.ceil(total/pageSize));
 const load=useCallback(async()=>{setLoading(true);setError("");try{const data=await fetchLLMProviders(page,pageSize,q);setRows(data.items);setTotal(data.total)}catch{setError("供应商读取失败，请检查后端服务后重试。")}finally{setLoading(false)}},[page,pageSize,q]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{fetchLLMCatalog().then(x=>setCatalog(x.providers)).catch(()=>setCatalog([]))},[]);
 const begin=(row?:LLMProviderConfig)=>{setCreated(null);setEditing(row??null);setPresetCode(row?.code??"");setForm(row?{code:row.code,name:row.name,base_url:row.base_url,api_key:"",enabled:row.enabled}:emptyForm);setOpen(true)};
 const selectPreset=(code:string)=>{setPresetCode(code);if(code==="custom"){setForm({...emptyForm});return}const p=catalog.find(x=>x.code===code);if(p)setForm(v=>({...v,code:p.code,name:p.name,base_url:p.base_url}))};
 const save=async()=>{setSaving(true);setError("");try{const saved=editing?await updateLLMProvider(editing.id,{name:form.name,base_url:form.base_url,api_key:form.api_key,enabled:form.enabled}):await createLLMProvider({code:presetCode==="custom"?undefined:form.code,name:form.name,base_url:form.base_url,api_key:form.api_key,enabled:form.enabled});setCreated(saved);await load()}catch{setError("保存失败，请确认接口地址、API Key 和供应商名称均已填写。")}finally{setSaving(false)}};
 return <section className="border" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}>
  <header className="flex flex-wrap items-start justify-between gap-3 border-b px-5 py-4" style={{borderColor:"var(--line)"}}><div><div className="flex items-center gap-2"><Server size={17}/><h2 className="text-lg font-medium">供应商配置</h2></div><p className="mt-1 text-sm" style={{color:"var(--ink-faint)"}}>供应商保存接口地址和密钥；模型必须关联这里已创建的供应商。</p></div><button type="button" onClick={()=>begin()} className="btn-gold flex items-center gap-2 px-4 py-2 text-sm"><Plus size={15}/>新增供应商</button></header>
  <div className="flex border-b px-5 py-3" style={{borderColor:"var(--line-soft)"}}><label className="flex max-w-sm flex-1 items-center gap-2 border px-3" style={{borderColor:"var(--line)"}}><Search size={15}/><input aria-label="搜索供应商" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="搜索供应商名称或代码" className="w-full bg-transparent py-2 outline-none"/></label></div>
  {error&&<p role="alert" className="border-b px-5 py-3 text-sm text-red-700" style={{borderColor:"var(--line-soft)"}}>{error}</p>}
  <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead><tr className="border-b" style={{borderColor:"var(--line-soft)"}}>{["供应商","代码","API Base URL","API Key","状态","操作"].map(x=><th key={x} className="px-5 py-3 font-medium">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={6} className="px-5 py-12 text-center">正在读取供应商…</td></tr>:rows.length===0?<tr><td colSpan={6} className="px-5 py-12 text-center">暂无供应商，请先新增供应商。</td></tr>:rows.map(item=><tr key={item.id} className="border-b last:border-0" style={{borderColor:"var(--line-soft)"}}><td className="px-5 py-4 font-medium">{item.name}</td><td className="px-5 py-4 font-mono text-xs">{item.code}</td><td className="px-5 py-4 font-mono text-xs">{item.base_url}</td><td className="px-5 py-4"><span className="inline-flex items-center gap-2 font-mono text-xs"><KeyRound size={13}/>{item.api_key_hint}</span></td><td className="px-5 py-4">{item.enabled?"已启用":"已停用"}</td><td className="px-5 py-4"><button type="button" onClick={()=>begin(item)}>编辑</button></td></tr>)}</tbody></table></div>
  <Pager total={total} page={page} pages={pages} pageSize={pageSize} onPage={setPage} onSize={x=>{setPageSize(x);setPage(1)}}/>
  {open&&<Modal title={editing?"编辑供应商":"新增供应商"} onClose={()=>setOpen(false)}>{created?<div><p role="status" className="border px-4 py-3 text-sm" style={{borderColor:"var(--line)",background:"var(--gold-soft)"}}>供应商“{created.name}”已保存。下一步可为它添加并设置调用优先级。</p><div className="mt-6 flex justify-end gap-3"><button className="btn-ghost px-4 py-2" onClick={()=>setOpen(false)}>稍后配置</button><Link href={`/admin/settings/models?provider_id=${created.id}`} className="btn-gold px-4 py-2">去配置模型</Link></div></div>:<><div className="grid gap-4">{!editing&&<label className="text-sm">常见供应商<select value={presetCode} onChange={e=>selectPreset(e.target.value)} className="mt-1 w-full border px-3 py-2" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}><option value="">请选择</option>{catalog.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}<option value="custom">自定义供应商</option></select></label>}<Field label="供应商名称" value={form.name} onChange={name=>setForm(v=>({...v,name}))}/><ReadOnlyCode value={editing?editing.code:presetCode==="custom"?"保存后由系统自动生成":form.code}/><Field label="API Base URL" value={form.base_url} onChange={base_url=>setForm(v=>({...v,base_url}))}/><Field label={editing?"更新 API Key（留空则不修改）":"API Key"} value={form.api_key} type="password" onChange={api_key=>setForm(v=>({...v,api_key}))}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.enabled} onChange={e=>setForm(v=>({...v,enabled:e.target.checked}))}/>启用供应商</label></div><Actions saving={saving} disabled={!presetCode||!form.name||!form.base_url||(!editing&&!form.api_key)} onCancel={()=>setOpen(false)} onSave={save}/></>}</Modal>}
 </section>
}

function Pager({total,page,pages,pageSize,onPage,onSize}:{total:number;page:number;pages:number;pageSize:number;onPage:(x:number)=>void;onSize:(x:number)=>void}){return <footer className="flex flex-wrap items-center justify-between gap-3 border-t px-5 py-4 text-sm" style={{borderColor:"var(--line-soft)"}}><span style={{color:"var(--ink-faint)"}}>共 {total} 条</span><div className="flex items-center gap-3"><label>每页 <select value={pageSize} onChange={e=>onSize(Number(e.target.value))} className="border px-2 py-1" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}><option>10</option><option>20</option><option>50</option></select></label><button className="btn-ghost px-3 py-1" disabled={page===1} onClick={()=>onPage(page-1)}>上一页</button><span>{page}/{pages}</span><button className="btn-ghost px-3 py-1" disabled={page===pages} onClick={()=>onPage(page+1)}>下一页</button></div></footer>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section role="dialog" aria-modal="true" aria-labelledby="provider-dialog-title" className="w-full max-w-xl border p-5 shadow-2xl" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}><h2 id="provider-dialog-title" className="text-xl">{title}</h2><div className="mt-5">{children}</div></section></div>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(x:string)=>void;type?:string}){return <label className="text-sm">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full border px-3 py-2" style={{borderColor:"var(--line)",background:"var(--bg-card)"}}/></label>}
function ReadOnlyCode({value}:{value:string}){return <div className="text-sm"><span>系统标识</span><div className="mt-1 border px-3 py-2 font-mono text-xs" style={{borderColor:"var(--line)",background:"var(--bg-soft)",color:"var(--ink-faint)"}}>{value||"选择供应商后自动填写"}</div><p className="mt-1 text-xs" style={{color:"var(--ink-faint)"}}>内部关联标识由系统维护，无需手工填写。</p></div>}
function Actions({saving,disabled,onCancel,onSave}:{saving:boolean;disabled:boolean;onCancel:()=>void;onSave:()=>void}){return <div className="mt-6 flex justify-end gap-3"><button className="btn-ghost px-4 py-2" onClick={onCancel}>取消</button><button disabled={disabled||saving} className="btn-gold px-4 py-2" onClick={onSave}>{saving?"保存中…":"保存"}</button></div>}
